plot & alumni
SCDB-IPDN/keuanganV2 pull request #162
Opened 2021-01-18 08:54 UTC by Dicky1

2021-01-19 04:29 UTC, restiyanada requested changes
1. Masukin Matkul, fakultas, prodinya berdasarkan nama aja, tapi IDnya juga keinput.
![image](https://user-images.githubusercontent.com/15180778/104987777-0d77ce80-5a49-11eb-9085-d64a19662b46.png)
2. ???
![image](https://user-images.githubusercontent.com/15180778/104988011-90992480-5a49-11eb-9fed-b1d5c4557a57.png)

2021-01-19 14:57 UTC, Dicky1 commented
udah ya

2021-01-20 02:07 UTC, restiyanada requested changes
1. error
![image](https://user-images.githubusercontent.com/15180778/105117240-c0563400-5afe-11eb-9ca9-95408452ee66.png)
2. ini masih salah, logicnya ngga gini.
![image](https://user-images.githubusercontent.com/15180778/105117301-db28a880-5afe-11eb-89f0-08bad2aab3f1.png)

2021-01-20 07:45 UTC, restiyanada reviewed
1. Nama dosen jadi pada ilang
![image](https://user-images.githubusercontent.com/15180778/105142823-9bc58080-5b2d-11eb-8e6b-b20e500ea4fe.png)
2.  Logic masih salah, seharusnya sehabis pilih fakultas prodi nya mengikuti prodi dari fakultas tersebut, begitu jga matkul mengikuti prodi yang dipilih (Urutannya Pilih Fakultas->Prodi->Matkul)
![image](https://user-images.githubusercontent.com/15180778/105143039-e21adf80-5b2d-11eb-9547-55fc8c8eb458.png)
![image](https://user-images.githubusercontent.com/15180778/105143117-feb71780-5b2d-11eb-9925-30d96ee578f2.png)
![image](https://user-images.githubusercontent.com/15180778/105143141-0971ac80-5b2e-11eb-97be-7f011179b7f9.png)

2021-01-26 19:38 UTC, closed without merging