udah ya kakak
SCDB-IPDN/keuanganV2 pull request #180
Opened 2021-02-03 02:03 UTC by Dicky1

2021-02-04 10:35 UTC, Dicky1 commented
Jangan lupa check ya kak ;)

2021-02-05 04:36 UTC, restiyanada commented
1. NIPnya ngga masuk.
![image](https://user-images.githubusercontent.com/15180778/106990162-4e404900-67a6-11eb-9e51-9b4d68b8166d.png)
2. button edit/deletenya pake icons aja, dan warna warna seragamin sama modul yang lain.

2021-02-05 04:40 UTC, Dicky1 commented
masuk kokk
![revisi1](https://user-images.githubusercontent.com/26633820/106990457-e0e0e800-67a6-11eb-9b0b-f98770cd922b.png)

2021-02-08 08:02 UTC, Dicky1 commented
gimana?

2021-02-08 09:14 UTC, hasnaasd requested changes
sks ini ambil dari permatkul aja dik, soalnya setiap matkul ada sksnya. ![image](https://user-images.githubusercontent.com/48850541/107199127-9bcbe880-6a28-11eb-8573-7185c99966a4.png)

2021-02-10 03:19 UTC, restiyanada requested changes
- select semesternya disable aja ya btw.

![image](https://user-images.githubusercontent.com/15180778/107459681-49eea400-6b89-11eb-849e-0ce16b85833b.png)

2021-02-10 03:51 UTC, closed without merging