Dicky
SCDB-IPDN/keuanganV2 pull request #68
Opened 2020-11-30 09:14 UTC by Dicky1

2020-12-01 02:31 UTC, restiyanada requested changes
![image](https://user-images.githubusercontent.com/15180778/100689900-f8bb7a80-33b7-11eb-9203-0c08bcd53cb1.png)

2020-12-01 08:01 UTC, restiyanada commented
![image](https://user-images.githubusercontent.com/15180778/100712905-143d7a00-33e6-11eb-95ab-b39614616b04.png)

2020-12-01 08:09 UTC, restiyanada commented
![image](https://user-images.githubusercontent.com/15180778/100713621-27047e80-33e7-11eb-8001-6fb174cda626.png)

2020-12-01 08:18 UTC, Dicky1 commented
masih ada yg error?

2020-12-01 08:20 UTC, restiyanada commented
![image](https://user-images.githubusercontent.com/15180778/100714682-aba3cc80-33e8-11eb-82a0-de2d6c134b09.png)

2020-12-01 09:03 UTC, restiyanada commented
![image](https://user-images.githubusercontent.com/15180778/100719055-b2cdd900-33ee-11eb-86b7-28c5ec396b16.png)
![image](https://user-images.githubusercontent.com/15180778/100719118-c9743000-33ee-11eb-85b1-cb8ef085801c.png)

2020-12-01 09:20 UTC, Dicky1 commented
jangan lupa di check kakak ;)

2020-12-02 02:21 UTC, restiyanada commented
1. sidebar belum bener 
![image](https://user-images.githubusercontent.com/15180778/100819966-ca08d700-347f-11eb-8b77-7b26d3cbd291.png)

2. upload realisasi belanja per jenis kegiatan belum.

2020-12-02 08:30 UTC, Dicky1 commented
dashboard praja di upload dulu sm yg peringkat per satker, barangkali pak teguh nanyain

2020-12-02 09:11 UTC, restiyanada commented
![image](https://user-images.githubusercontent.com/15180778/100852369-01e04080-34b9-11eb-9696-364cd535b4c1.png)

2020-12-02 09:20 UTC, restiyanada commented
1. ini hapus dulu aja, karena gue mau ambil yang **dashboard** dulu.
![image](https://user-images.githubusercontent.com/15180778/100853401-4ddfb500-34ba-11eb-80fc-627a30135dc2.png)

2. benerin highlightnya 
![image](https://user-images.githubusercontent.com/15180778/100853249-20930700-34ba-11eb-9fe0-c4e0bd7e7a3b.png)

2020-12-02 10:07 UTC, restiyanada approved these changes

2020-12-02 10:07 UTC, merged